Round 6
Basystyy/oop pull request #4
Opened 2022-09-21 16:38 UTC by Basystyy

2022-10-18 20:09 UTC, d1ma-angel approved these changes

2022-10-18 20:09 UTC, d1ma-angel commented on app.rb
> +# require_relative './station'
У тебя приложение не запускается `ruby main.rb`
```
/trains/train.rb:3:in `<class:Train>': uninitialized constant Train::Manufacturer (NameError)

include Manufacturer
```

2022-10-18 20:09 UTC, d1ma-angel commented on route.rb
> +    register_instance
лучше регистрировать инстанс уже в конце метода, когда ты уверен, что все, что выполнялось в методе до регистрации отработало верно и ничего не упало. То же самое касается вызова `register_instance`  в других классах

2022-10-18 20:09 UTC, d1ma-angel commented on train.rb
> +    @@trains = []
Почему тут решил поместить это внутри self, а в Station снаружи?

2022-10-20 07:52 UTC, Basystyy commented on route.rb
> +    register_instance
Логично, поправил

2022-10-20 07:52 UTC, Basystyy commented on train.rb
> +    @@trains = []
Не обратил внимания. Перенес вне класса

2022-10-20 07:52 UTC, Basystyy commented on app.rb
> +# require_relative './station'
Уже запускается))) main.rb ничего не знал про новые файлы

2022-10-30 07:34 UTC, d1ma-angel requested changes

2022-10-30 07:34 UTC, d1ma-angel commented on menu.rb
> +end
класс закрылся раньше времени. Получается так, что у тебя методы живут вне его.

2022-10-30 07:34 UTC, d1ma-angel commented on menu.rb
> +  rescue => error
На самом деле очень плохой тон делать rescue от всех ошибок, а не от какого-то конкретного типа. Может случиться так, что упадет что-то не в валидации, а дальше. И он просто скажет, что поезд не создан. `puts #{error}` проблему не решает. Это допустимо тут только как учебный вариант.

2022-10-30 07:34 UTC, d1ma-angel commented on route.rb
>  class Route
Ни в одном из классов не нашел метод valid?

2022-10-30 07:34 UTC, d1ma-angel commented on train.rb
> +  NUMBER_CARGO = /^cargo\d+$/i
Формат единый для всех типов поездов. Описанное не отвечает требованиям к формату в ТЗ.

2022-10-30 07:34 UTC, d1ma-angel commented on train.rb
> +    raise "Отсутствие номера поезда недопустимо!" if name == ''
Теоретически эту и следующую проверку можно слить в одно, но тут по желанию

2022-10-30 07:34 UTC, d1ma-angel commented on train.rb
> +    raise "Такой номер поезда уже существует, выберите другой." if self.class.find(name) != []
Если ты решил избавиться от имени поезда и оставить только его номер, то и переменная везде должна быть `number`, не `name`.

2022-10-30 07:34 UTC, d1ma-angel commented on store.rb
> +    @store << name
лучше `record` или `objekt`, а не `name`

2022-10-30 07:34 UTC, d1ma-angel commented on route.rb
> +  def validate!
не проверяешь, что первая и последняя станция существуют. Что они не одно и то же. И что это вообще станции, а не объект поезда туда передан.

2022-10-30 07:34 UTC, d1ma-angel commented on route.rb
> +    raise "Отсутствие названия маршрута недопустимо!" if name == ''
Теоретически эту и следующую проверку можно слить в одно, но тут по желанию

2022-10-30 07:34 UTC, d1ma-angel commented on station.rb
> +    raise "Отсутствие названия станции недопустимо!" if name == ''
Теоретически эту и следующую проверку можно слить в одно, но тут по желанию

2022-10-30 07:34 UTC, d1ma-angel commented on station.rb
>      trains.each do |train|
Красивше было бы сначала выгрести все поезда именно этого типа, а уже потом по ним проходиться с помощью `.each`

2022-11-09 09:18 UTC, Basystyy commented on menu.rb
> +end
Поправил. Это "последыш" моей попытки перевести всё меню в методы класса

2022-11-09 09:19 UTC, Basystyy commented on menu.rb
> +  rescue => error
поправил на StandartError. Норм?

2022-11-09 09:24 UTC, Basystyy commented on route.rb
>  class Route
Добавил в Station

2022-11-09 09:36 UTC, Basystyy commented on train.rb
> +  NUMBER_CARGO = /^cargo\d+$/i
Поправил в соответствии с требованиями ТЗ

2022-11-09 10:08 UTC, Basystyy commented on station.rb
>      trains.each do |train|
Посмотри пожалуйста, как поправил. Как на меня - норм. И непонятно, почему раньше так не сделал)))

2022-11-09 10:18 UTC, Basystyy commented on route.rb
> +  def validate!
Поставил проверку и добавил проверку при добавлении станции в маршрут

2022-11-16 12:49 UTC, d1ma-angel approved these changes

2022-11-16 12:49 UTC, d1ma-angel commented on route.rb
> +    self.class.add_object(self)
Теоретически можно было создать инстанс метод в модуле Store по аналогии как ты это делал в instance_counter и дергать его, чтобы каждый раз не писать эту нетривиальную конструкцию в нескольких классах

2022-11-16 12:49 UTC, d1ma-angel commented on train.rb
> +  NAME_FORMAT = /^[a-z0-9]{3}-?[a-z0-9]{2}/i
Молодец, только $ в конце забыл, ибо иначе он и такое проглотит 478-584444

2022-11-16 12:49 UTC, d1ma-angel commented on station.rb
> +  def valid?
этот метод лучше бы в модуль вытащить и потом прикрутить этот модуль везде где ты используешь валидации

2022-11-16 12:49 UTC, d1ma-angel commented on route.rb
> +    @stations.each.with_index(1) do |name|
тут with_index явно лишний. Ну и лучше все-таки .is_a? где есть такая возможность, а не class.to_s
Это связано с работой оперативки

2022-11-16 12:49 UTC, d1ma-angel commented on train.rb
>    attr_reader :station, :route, :number, :speed, :wagons, :name
`:number` - не забывай подчищать атрибуты, которые уже не существуют

2022-11-16 12:49 UTC, d1ma-angel commented on station.rb
> +      puts train.name if train.class == CargoTrain
лучше `.is_a?`

2022-11-22 09:47 UTC, Basystyy commented on station.rb
> +  def valid?
Логичною valid? перенес в Store

2022-11-22 09:49 UTC, Basystyy commented on route.rb
> +    self.class.add_object(self)
Логично, так код не будет повторяться

2022-11-22 10:07 UTC, Basystyy commented on route.rb
> +    @stations.each.with_index(1) do |name|
Заменил, посмотри плз

2022-11-22 10:08 UTC, Basystyy commented on train.rb
>    attr_reader :station, :route, :number, :speed, :wagons, :name
Да, спасибо. Убрал

2022-11-22 10:10 UTC, Basystyy commented on station.rb
> +      puts train.name if train.class == CargoTrain
Заменил

2022-11-22 10:24 UTC, merged